FROM node:18 as builder

RUN apt-get update

RUN apt-get install sqlite3 

WORKDIR /usr/src/my-app

COPY package*.json .

FROM --platform=amd64 node:18 as production

COPY --from=builder ./usr/src/my-app ./

CMD ["npm", "run", "test"]