FROM node:18 as builder

RUN apt-get update

RUN apt-get install sqlite3 

WORKDIR /usr/src/my-app

COPY . .

FROM --platform=amd64 node:18 as production

COPY --from=build ./usr/src/my-app/package.json ./package.json
COPY --from=build ./usr/src/my-app/package-lock.json ./yarn.json


RUN yarn install

CMD ["yarn", "test"]