version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command:
      - |
        yarn add sqlite3 --save
        yarn test
    depends_on:
      - redis
  redis:
    image: 'redis:alpine'
